from . import account_bank_statement
from . import account_move
from . import customizations
from . import dashboard
from . import mrp_production
from . import partner
from . import product
from . import project
from . import purchase
from . import sale
from . import stock_move
from . import stock_picking
