from . import account_payment
from . import employee_schedule_log
from . import hr_allowance
from . import hr_attendance
from . import hr_benefits
from . import hr_bonus
from . import hr_contract
from . import hr_contract_salary
from . import hr_deductions
from . import hr_employee
from . import hr_fines
from . import hr_job
from . import hr_leave_allocation
from . import hr_loans
from . import hr_payslip
from . import hr_rates
from . import resource_calendar
