# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    'name': 'Production Planner',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '90',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['cus_stock'],
    'data': [
        'data/cron.xml',
        'data/ir_sequence_data.xml',
        'data/nd2_data.xml',
        'data/nd4_data.xml',
        'reports/report_picklist.xml',
        'reports/report_qr_code.xml',
        'reports/reports.xml',
        'security/ir.model.access.csv',
        'views/assembly_process_views.xml',
        'views/bom_tool_lines_views.xml',
        'views/mrp_bom_view.xml',
        'views/mrp_production_view.xml',
        'views/mrp_workorder_views.xml',
        'views/production_planner_views.xml',
        'views/product_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
        'wizards/add_mrp_production_bulk_tagging.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
