from . import purchase_history
from . import receipt_history
from . import landed_cost_history
from . import manufacturing_history
from . import scrap_history
from . import sale_history
from . import quarterly_consumption
from . import taraz_part_database
from . import weight_database
from . import product
from . import product_duplicate_names
from . import mrp_bom
from . import hs_codes
from . import res_config_settings
from . import partner
from . import inventory_report
