# -*- coding: utf-8 -*-

{
    'name': 'Payroll Customizations',
    'version': '13.0.1.0.0',
    'summary': 'Customization in payroll module',
    'sequence': '40',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['customizations'],
    'data': [
        'data/accounting_data.xml',
        'data/cron.xml',
        'data/hr_loan_sequence.xml',
        'data/report_paper_format_data.xml',
        'security/ir.model.access.csv',
        'reports/employee_badge_report.xml',
        'reports/hr_bonus_batches_report.xml',
        'reports/hr_bonus_batches_report_template.xml',
        'reports/hr_payslips_batches_report.xml',
        'reports/hr_payslips_batches_report_template.xml',
        'reports/reports.xml',
        'reports/wht_return_certificate.xml',
        'views/account_payment_views.xml',
        'views/hr_allowance_views.xml',
        'views/hr_attendance_views.xml',
        'views/hr_benefits_views.xml',
        'views/hr_bonus_views.xml',
        'views/hr_contract_salary_views.xml',
        'views/hr_contract_views.xml',
        'views/hr_deductions_view.xml',
        'views/hr_employee_views.xml',
        'views/hr_fines_views.xml',
        'views/hr_job_views.xml',
        'views/hr_leave_views.xml',
        'views/hr_loans_views.xml',
        'views/hr_payslip_views.xml',
        'views/hr_rates_views.xml',
        'views/resource_calendar_views.xml',
        'wizards/add_hr_contract_bulk_tagging.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
