# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    'name': 'Cable Assembly',
    'version': '13.0.1.0.0',
    'summary': 'Manage Cable Assemblies',
    'sequence': '20',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': [
        'product', 'stock', 'project',
        'odoo_images', 'report_xlsx',
    ],
    'data': [
        'data/sequence_record.xml',
        'reports/report_cut_list.xml',
        'reports/report_demand_list.xml',
        'reports/report_demand_list_procurement.xml',
        'reports/reports.xml',
        'security/ir.model.access.csv',
        'views/cable_manufacturing_view.xml',
        'views/connector_view.xml',
        'views/harness_view.xml',
        'views/product_view.xml',
        'views/wire_core_views.xml',
        'views/wire_view.xml',
        'views/wiring_bom_line_view.xml',
        'views/wiring_bom_view.xml',
        'views/menus.xml',
        'wizards/add_cable_assembly_bom_line_bulk_duplication.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
