# -*- coding: utf-8 -*-

{
    'name': 'BoM Tool',
    'version': '13.0.1.0.0',
    'summary': 'BoM Tool',
    'sequence': '50',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['cus_product_360_view'],
    'data': [
        'data/ir_sequence_data.xml',
        'data/subscription_template.xml',
        'security/ir.model.access.csv',
        'reports/reports.xml',
        'views/automation_rules_views.xml',
        'views/bom_base_views.xml',
        'views/bom_blocks_views.xml',
        'views/bom_lines_views.xml',
        'views/bom_tool_views.xml',
        'views/menus.xml',
        'views/product_views.xml',
        'views/variant_processing_views.xml',
        'wizards/import_bom_files_views.xml',
        'wizards/add_bom_line_views.xml',
        'wizards/add_block_lines_views.xml',
        'wizards/add_bom_lines_bulk_tagging.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
