{
    'name': 'Custom Tags',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '10',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['base'],
    'data': ['security/ir.model.access.csv'],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
}