{
    'name': 'MRP Kanban',
    'version': '13.0.1.0.0',
    'summary': 'Manufacturing Orders Kanban View Update',
    'sequence': '120',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'license': 'LGPL-3',
    'depends': [
        'cus_mrp_children',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/mrp_production_stage_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_workorder_views.xml',
        'views/stock_picking_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}