# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    'name': 'Customizations',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Customization',
    'sequence': '30',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': [
        'hr', 'web', 'mrp', 'utm', 'base', 'note', 'sale', 'mail', 'stock', 'board', 'hr_attendance', 'resource',
        'payment', 'product', 'project', 'account', 'contacts', 'delivery', 'om_hr_payroll_account', 'crm',
        'hr_holidays', 'hr_timesheet', 'base_automation', 'stock_landed_costs', 'project_task_subtask', 'bi_auto_invoice',
        'cus_octopart_connector',
        'cable_assembly',
        'custom_tags',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/accounting_data.xml',
        'data/automated_actions.xml',
        'data/cron.xml',
        'data/decimal_accuracy.xml',
        'data/employee_data.xml',
        'data/products_data.xml',
        'data/sequence_records.xml',
        'data/time_off_data.xml',
        'reports/end_user_document.xml',
        'reports/invoice_banking_report.xml',
        'reports/invoice_report.xml',
        'reports/reports.xml',
        'reports/sales_tax_invoice.xml',
        'views/account_account_view.xml',
        'views/account_bank_statement_view.xml',
        'views/account_move_view.xml',
        'views/account_payment_view.xml',
        'views/company_view.xml',
        'views/contacts_view.xml',
        'views/country_region_views.xml',
        'views/dashboard_views.xml',
        'views/delivery_carrier_views.xml',
        'views/invoice_view.xml',
        'views/letter_head_layout.xml',
        'views/maintenance_views.xml',
        'views/mass_mailing_views.xml',
        'views/mrp_bom_view.xml',
        'views/mrp_production_view.xml',
        'views/note_view.xml',
        'views/payment_view.xml',
        'views/processes_views.xml',
        'views/products_view.xml',
        'views/project_timer_static.xml',
        'views/project_views.xml',
        'views/purchase_views.xml',
        'views/sale_order_view.xml',
        'views/shipping_box_views.xml',
        'views/shipping_zone_views.xml',
        'views/stations_view.xml',
        'views/stock_landed_cost_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_type_views.xml',
        'views/stock_picking_views.xml',
        'views/stock_scrap_view.xml',
        'views/stock_valuation_layer_views.xml',
        'views/utm_campaign_view.xml',
        'wizards/mailing_list_contact_add_views.xml',
        'wizards/purchase_order_discount_view.xml',
        'wizards/purchase_order_shipping_view.xml',
        'wizards/task_tags_view.xml',
    ],
    'images': ['static/images/icon.png'],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
