{
    'name': 'Procurement Tool',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '100',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['cus_production_planner'],
    'data': [
        'data/cron.xml',
        'data/ir_sequence_data.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'reports/reports.xml',
        'views/component_list_views.xml',
        'views/internal_demand_rm_views.xml',
        'views/procurement_cycle_views.xml',
        'views/menus.xml',
        'views/partner_views.xml',
        'views/purchase_views.xml',
        'views/res_config_settings_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
        'wizards/alt_and_comp_selection_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
