# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    'name': 'Accounts',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '60',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['cus_bom_tool'],
    'data': [
        'data/cron.xml',
        'security/ir.model.access.csv',
        'reports/reports.xml',
        'reports/apv_and_vi_document.xml',
        'views/account_bank_statement_views.xml',
        'views/account_move_luca_view.xml',
        'views/account_move_view.xml',
        'views/account_payment_view.xml',
        'views/account_views.xml',
        'views/menus.xml',
        'views/partner_view.xml',
        'views/purchase_order_views.xml',
        'views/res_currency_views.xml',
        'views/sale_order_views.xml',
        'wizards/add_move_source_views.xml',
        'views/account_journal_dashboard_view.xml',
        'wizards/add_bulk_tagging.xml',
        'wizards/add_luca_view_bulk_tagging.xml',
        'wizards/add_account_move_line_bulk_tagging.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
