{
    'name': 'MRP Workorder',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '100',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'license': 'LGPL-3',
    'depends': [
        'cus_production_planner',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/mrp_workcenter_views.xml',
        'views/mrp_workorder_stage_views.xml',
        'views/mrp_workorder_views.xml',
        'views/serial_products_views.xml',
        'wizards/add_mrp_workorder_bulk_tagging.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
