# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
{
    'name': 'Logistics Tracking',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '70',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['cus_accounts'],
    'data': [
        'data/consolidation_tracking_sequence.xml',
        'data/cron.xml',
        'security/ir.model.access.csv',
        'security/rules.xml',
        'reports/certificate_of_origin.xml',
        'reports/certificate_of_origin_multi.xml',
        'reports/delivery_labels.xml',
        'reports/letter_to_customs.xml',
        'reports/product_scan_codes.xml',
        'reports/quality_certificate.xml',
        'reports/report_packing_labels.xml',
        'reports/report_packing_list.xml',
        'reports/report_receipt_order.xml',
        'reports/report_returnslip.xml',
        'reports/request_letter_for_CCI.xml',
        'reports/routing_order_form.xml',
        'reports/shipper_undertaking.xml',
        'reports/shipping_invoice.xml',
        'reports/undertaking.xml',
        'reports/warranty_certificate.xml',
        'reports/accessories_labels.xml',
        'reports/final_packing_checklist.xml',
        'reports/reports.xml',
        'views/account_move_views.xml',
        'views/consolidation_tracking_views.xml',
        'views/country_of_origin_rules_views.xml',
        'views/delivery_views.xml',
        'views/free_zone_operations_views.xml',
        'views/logistics_route_views.xml',
        'views/logistics_tracking_views.xml',
        'views/partner_views.xml',
        'views/product_views.xml',
        'views/purchase_views.xml',
        'views/res_country_views.xml',
        'views/stock_landed_cost_views.xml',
        'views/stock_move_views.xml',
        'views/stock_picking_views.xml',
        'views/menus.xml',
        'wizards/add_free_zone_bulk_tagging.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
