# Copyright 2015 ACSONE SA/NV (<http://acsone.eu>)
{
    'name': 'Product 360 View',
    'version': '13.0.1.0.0',
    'summary': 'Odoo Custom Model',
    'sequence': '40',
    'category': 'Customization',
    'author': 'Taraz Technologies Pvt. Ltd.',
    'maintainer': 'Taraz Technologies Pvt. Ltd.',
    'company': 'Taraz Technologies Pvt. Ltd.',
    'website': 'https://www.taraztechnologies.com/',
    'depends': ['customizations'],
    'data': [
        'data/cron.xml',
        'data/digikey_api_token.xml',
        'reports/reports.xml',
        'reports/report_bom_details.xml',
        'reports/inventory_sale_report_template.xml',
        'reports/reports.xml',
        'security/ir.model.access.csv',
        'views/hs_codes_views.xml',
        'views/inventory_report_views.xml',
        'views/product_duplicate_names.xml',
        'views/product_views.xml',
        'views/purchase_history_views.xml',
        'views/receipt_history_views.xml',
        'views/landed_cost_history_views.xml',
        'views/taraz_part_database_views.xml',
        'views/weight_database_views.xml',
        'views/manufacturing_history_views.xml',
        'views/sale_history_views.xml',
        'views/scrap_history_views.xml',
        'views/quarterly_consumption_views.xml',
        'views/res_config_settings_views.xml',
        'views/mrp_bom_views.xml',
        'views/res_partner_views.xml',
        'wizards/alternate_mass_usage_views.xml',
        'wizards/compromised_mass_usage_views.xml',
        'wizards/merge_taraz_part_views.xml',
        'wizards/add_product_product_bulk_tagging.xml',
        'wizards/add_product_template_bulk_tagging.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
